
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-idel: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
    timeout: 30000
server:
  port: 8081